### ISSUE TITLE
add slider to date range filter

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#225]
See page 5 of the design comp: https://share.getty.edu/download/attachments/69928104/RP_DesignComps_v2.1.pdf?api=v2

**Comment by kristenGRI** [comment]
@susanley committed to the branch to help with the styling. There are currently two functional bugs I noticed (hopefully I don't do anything by accident to cause them somehow!) 

- by default, both handles are set to 0 instead of 0 and current year

- After you move either or both sliders from the 0 position, you can never get back to 0 using the sliders. (the lowest it goes is 1085)

Let me know if you have any questions!
