### ISSUE TITLE
make facetable fields in item detail page clickable

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#238]
From the wireframe document:

> 3.1 Information that can also be used
to filter (e.g.: type, subject, etc) Is
clickable and will launch a search for
that content (ex: Clicking “book” will
launch a search for all books)

This could be complex as we are using separate fields for faceting in some cases.

**Comment by jfranco-gri** [comment]
I've been working on this, and got it partly working, but it's proving a little difficult. When there's more than one facet for a particular field, it's difficult to know which facet term (as Elasticsearch knows it) to search on. Simply using the text isn't working since it doesn't always use the same name. For instance, in a book detail page, a subject facet might be "Portrait miniatures, American." but elasticsearch encodes that facet as "Portrait miniatures, American" (with elasticsearch, there is no period at the end). Other times, it's wildly different. I'll have to figure out a way to map between the data.
