### ISSUE TITLE
implement API search functionality

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#323]

**Comment by jfranco-gri** [comment]
I wrote a Books APIView for the search query api and got search queries working. All the various search options work including facets and advanced search fields.  It can handle queries like this and can return a response in either xml or json:

`http://127.0.0.1:8000/api/books/q=art&from=0&size=25&sort=title_desc&date_gte=1900&language=English&adv_contributor=getty`

I rewrote all the functions in esQueryBuilder in python and it builds the elastic search query on the backend now and runs that query in elastic search.  For this I used elasticsearch-py instead of elasticsearch-dsl because the dsl version didn't have very good examples in the documentation and it said faceted search was still in an 'experimental' phase and was likely to change.  elasticsearch-py was pretty simple to use. It returns a dictionary response object so it was easy to turn that into json and should be easy to parse into other formats.
