### ISSUE TITLE
more zombie filters when using Advanced Search

### ISSUE THREAD

**Issue by jfranco-gri** [gri-is/portal#413]
To reproduce:

1) Run an empty search
2) On the search results page, set date range to 1900-1920. You will see the date facet chip appear in the search bar.
3) Click Advanced Search
4) Set a Filter field. For example, use Language: English
5) Click Search

You will see that along with the Language filter, we still have the Date filter applied. This also happens with pagination.

**Comment by adamcee** [comment]
We currently are not resetting SearchService opts if the user navigates away from the search results page or on the Advanced Search page.

This raises the product design question of: *If I initiate an Advanced Search from the Search Results page, should that be an extension of my existing search or a brand new one?* 

**If we want Advanced Search to always be a new search...**
- I think this can be fixed by calling `SearchService.newSearch()` in the Advanced Search Controller instead of `SearchService.updateSearch()`.

- Also, once the query params are the canonical source of search options this issue should be resolved.

**Comment by jfranco-gri** [comment]
Well if facets, pagination, etc are still lingering in the Search Service options (as they are now, which is causing the incorrect behavior), they will make their way into the URL too...

**Comment by adamcee** [comment]
True. We would need to clear the SearchService opts at an appropriate point.

I still think this is a product design question, because we never specified an Advanced Search should clear existing Search options.

What if the user wants to use advanced search to filter their existing search? 
I'm not saying that that should be the case, just that this is a use case we haven't discussed.  

Yeah, if we don't want this behavior we can clear SearchService options when the Advanced Search controller loads. Or handle clearing SearchService options in a more consistent way.

**Comment by adamcee** [comment]
**Conclusions** **--** As per our discussion offline ....

1. Pagination definitely needs to be reset when executing an advanced search from the advanced search page. 
2. @kristenGRI Doublechecking -- if the user navigates to Advanced Search from the Search Results, and then does an advanced search, should it clear existing search options (facets, date range, query terms, other advanced fields)?

**Comment by joshuago78** [comment]
Yes, going to Advanced search should be the like going to the home page: a clean slate.
