### ISSUE TITLE
Inidicate if a facet chip has zero limiting results

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#423]
- If a facet no longer has results it is removed from the sidebar
  - But it remains in the search bar
- Removing it from the search bar would be even more confusing
  - So we need to indicate that it is no longer contributing to the result set
  - Some ideas for this:
    - strikethrough text
    - grayed out color or red color?

- [x] step1 : @kristenGRI will decide on appearance, then reassign the issue to a developer
- [x] step2: the developer will implement the necessary behavior

**Comment by kristenGRI** [comment]
Attaching two options for indicating a facet is no longer yielding results. I kind of like the grayed out version better because it looks more "inactive." But I could see wanting something that draws more attention to the fact that the facet isn't working as well so there is a red option. 
![inactive facet_v1](https://cloud.githubusercontent.com/assets/15019503/14972836/5c5794a2-1095-11e6-99bf-5884645a7ce9.png)
![inactive facet_v2](https://cloud.githubusercontent.com/assets/15019503/14972837/5c5a61a0-1095-11e6-9d1d-785f6a6af66f.png)

**Comment by kristenGRI** [comment]
Noting that we decided to go with v1 (gray facet chip color with strike through facet chip text) Facet chip gray is #ccc.
