### ISSUE TITLE
SEO & indexing

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#450]
- [ ] do we need a headless browser for search index crawling?
- [x] do we need a site map? **Yes**. See #490 for description of sitemap.
- [x] write robots.txt file

**Comment by adamcee** [comment]
Note from team slack conversation on Monday 5/23:
- We don't want web crawlers on the results page. Goal is to give them site map of item detail pages.

**Comment by adamcee** [comment]
**Resources List**
https://www.npmjs.com/package/gulp-sitemap

**Comment by adamcee** [comment]
I have spec'd out what we need to do for the sitemap on a separate issue. I am still trying to figure out what we should dis-allow google crawler to see. Googlebot now can understand javascript, and they say you should let it crawl the `.js` code but I'm not entirely sure what that means in our case - esp. as we don't want it repeatedly hitting the search results page.

I have read conflicting information about pre-rendering html to serve just for googlebot (which can be done w/headless browser or other ways). Seems like Google's advice tends more towards "just implement html5Mode well and let us crawl your `.js`" but I'm not 100%.

https://builtvisible.com/javascript-framework-seo/

**For non-google crawlers we probably would need to prerender and tell the server to serve the prerendered page to crawlers.** Since item detail pages are most important we may want to start there or investigate making those pages static.
