### ISSUE TITLE
site is not responsive on mobile phone

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#460]
You can now test it out on http://portalbeta.getty.edu

So far I have only tested this on Chrome on a Samsung Note 5 phone.

**Comment by jfranco-gri** [comment]
It is not responsive on my iPhone 4 either. 

I was looking into this and it seems mobile browsers do some scaling of webpages so that the entire page fits on the screen. However, it means that it never hits our css rules that provide the responsive behavior for smaller screen sizes. We need to add something like this to the html:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

We might also need to set `maximum-scale=1.0, minimum-scale=1.0`

**Comment by joshuago78** [comment]
Closed with PR #463
