### ISSUE TITLE
make modal size dynamic

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#496]
Annie and Kathleen want to know if we can make the modal window resize as the browser window is adjusted. I'm not sure how much effort this would involve. It is definitely a lower priority than our current tasks.

**Comment by adamcee** [comment]
For me in Chrome on portalbeta, the modal search window does resize as I shrink the browser past a certain point. Don’t know if that’s their specific use case or not.
On May 31, 2016, at 10:45 AM, Joshua Gomez <notifications@github.com<mailto:notifications@github.com>> wrote:


Annie and Kathleen want to know if we can make the modal window resize as the browser window is adjusted. I'm not sure how much effort this would involve. It is definitely a lower priority than our current tasks.

**Comment by joshuago78** [comment]
Yes, it is responsive as it shrinks, but I think they want something that will show more results if the window is big enough.

**Comment by adamcee** [comment]
Ah - gotcha! Somewhat related to that, were we thinking of using pagination instead of scrolling in the facet modal search box at some point? Doing that could change their user experience in this area.

Right now I think we have a fixed limit of 1000 on facet options returned per category. Going to create another issue to discuss and track that ...
