### ISSUE TITLE
check API error in IE

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#612]
See http://portal.getty.edu/api/book/bnf_bpt6k6484170m in IE as an example.

**Comment by joshuago78** [comment]
Here is the error message from Django:
```django
Template error:
In template /apps/portal/ENV/lib/python3.4/site-packages/rest_framework/templates/rest_framework/base.html, error at line 49
   Non-reversible reg-exp portion: '(?!'

   39 :               <a class='navbar-brand' rel="nofollow" href='http://www.django-rest-framework.org'>
   40 :                   Django REST framework
   41 :               </a>
   42 :             {% endblock %}
   43 :           </span>
   44 :           <ul class="nav navbar-nav pull-right">
   45 :             {% block userlinks %}
   46 :               {% if user.is_authenticated %}
   47 :                 {% optional_logout request user %}
   48 :               {% else %}
   49 :                  {% optional_login request %} 
   50 :               {% endif %}
   51 :             {% endblock %}
   52 :           </ul>
   53 :         </div>
   54 :       </div>
   55 :     {% endblock %}
   56 : 
   57 :     <div class="container">
   58 :       {% block breadcrumbs %}
   59 :         <ul class="breadcrumb">
```

**Comment by joshuago78** [comment]
For some reason it is trying to render the base.html template instead of returning our serialized data.

**Comment by joshuago78** [comment]
Interestingly, http://grpdev.getty.edu/api/book/raw/bnf_bpt6k6484170m manages to return without error, but again it is rendering the Django REST frameworks html view, not the raw serialized data.

**Comment by jfranco-gri** [comment]
It seems like it is using the REST framework's api renderer by default, instead of the xml or json renderer. It says in the REST framework documentation that it chooses which renderer to use based on the Accept header. Could IE be requesting a different renderer than firefox or chrome, such as the api renderer? When I use the api renderer in chrome, I get the same error (add .api to that api call).

The renderers are listed in the settings.py file like so:

```
REST_FRAMEWORK = {
  'DEFAULT_RENDERER_CLASSES': (
    'rest_framework.renderers.JSONRenderer',
    'rest_framework_xml.renderers.XMLRenderer',
    'rest_framework.renderers.BrowsableAPIRenderer',
    'api.renderers.RISRenderer',
  )
}
```

**Comment by jfranco-gri** [comment]
So it's not that there is a bug in IE but not firefox or chrome. The bug exists in chrome and firefox as well, but it's that by default IE exposes the bug, while by default chrome and firefox do not.

The API renderer definitely used to work (I have used it quite extensively as it prints out the data in a human-readable way) so something must have changed, perhaps in our data.

**Comment by jfranco-gri** [comment]
It's having issues with this url pattern:

`url(r'^book/(?!raw/)(?P<id>(?:(?!.json|.xml|.api).)*)$', Book.as_view(), name='book'),`

I know this is the "non-raw" url, so it might not make sense why this would cause the request for raw data to fail, but commenting out this url makes the raw url work. It's specifically this section `(?!raw/)` because removing that makes the `book/...` api url work, but then `book/raw/` doesn't match with the correct url (it matches with the non-raw url). 

Maybe we should revisit these url paths and choose a different one for book/raw? I think it's always been confusing to differentiate between the two data types (book/ vs book/raw/) and as we can see, it causes issues with the url patterns.

Or we could figure out a fix for the regex.

**Comment by joshuago78** [comment]
I think the urls could be rewrtten without the `(?!raw/)` portion in the regex.
```python
url(r'^book/raw/(?P<id>(?:(?!.json|.xml|.api|.ris).)*)$', Raw.as_view(), name='raw'),
url(r'^book/(?P<id>(?:(?!.json|.xml|.api).)*)$', Book.as_view(), name='book'),
```
