### ISSUE TITLE
Do not store empty (or See All) searches in Recent Searches

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#614]
These can really fill up the search history and (in my opinion) offer no value, so we should ignore them.
- Perhaps we can put a disclaimer at the top of the Recent Searches tab that it is not storing "See All" searches.
  - If we do that, perhaps we should also add code that removes them from existing histories.

@kristenGRI please respond if you agree or have additional comments before @jfranco-gri begins work on this.

**Comment by kristenGRI** [comment]
@joshuago78 I agree that it seems pointless to store them since they offer no real value that I can see. I'm not even sure we need the disclaimer text. I almost feel like no one would notice it wasn't storing empty searches. 

Another thought (and I feel like we've talked about this) but should we even be storing duplicate searches?

**Comment by joshuago78** [comment]
Yes, de-duplication could also be useful. But we would have to remove the older search and keep the newer one, rather than the other way around. Otherwise, that search could be hard to find under a bunch of other newer searches.

I leave it to @jfranco-gri to decide if she wants to tackle de-duplication now or in a separate issue.

**Comment by kristenGRI** [comment]
Also agree. Same searches "should float to the top" and delete the older duplicate. But yeah, this might be another ticket.
