### ISSUE TITLE
remove link to old Portal

### ISSUE THREAD

**Issue by joshuago78** [gri-is/portal#622]
@alyxrossetti I figured you would be happy to have this one assigned to you as it means you no longer have to perform item loads to the old Portal.

**Comment by alyxrossetti** [comment]
@joshuago78 I am stoked!  Quick question - do you want me to leave the "container" empty so that we still have some space at the bottom of the page or should I remove it all together?  See screenshots below ...

<img width="1440" alt="text_removed" src="https://cloud.githubusercontent.com/assets/9535150/18754261/e96a6082-809c-11e6-90ab-61f87c5a6523.png">
<img width="1440" alt="container_removed" src="https://cloud.githubusercontent.com/assets/9535150/18754235/d5c3659c-809c-11e6-959e-33c0fca599b4.png">

**Comment by alyxrossetti** [comment]
@joshuago78 @kristenGRI Thoughts on this?

**Comment by joshuago78** [comment]
I prefer the space

**Comment by kristenGRI** [comment]
@alyxrossetti Agreed. It's nice to have the space between the pagination and the footer.
